"""empty message

Revision ID: 567149d43c1e
Revises: be3a95fdcc5e
Create Date: 2023-06-25 13:08:09.216458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567149d43c1e'
down_revision = 'be3a95fdcc5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identification', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('long',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('identification_mini', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('long', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identification_mini', schema=None) as batch_op:
        batch_op.drop_column('long')
        batch_op.drop_column('lat')

    with op.batch_alter_table('identification', schema=None) as batch_op:
        batch_op.alter_column('long',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('lat',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
