"""empty message

Revision ID: 7b2dad2d7478
Revises: 567149d43c1e
Create Date: 2023-06-27 09:31:38.480756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2dad2d7478'
down_revision = '567149d43c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('img_1', sa.String(length=100), nullable=False),
    sa.Column('img_2', sa.String(length=100), nullable=True),
    sa.Column('img_3', sa.String(length=100), nullable=True),
    sa.Column('img_4', sa.String(length=100), nullable=True),
    sa.Column('img_5', sa.String(length=100), nullable=True),
    sa.Column('organ_1', sa.String(length=30), nullable=False),
    sa.Column('organ_2', sa.String(length=30), nullable=True),
    sa.Column('organ_3', sa.String(length=30), nullable=True),
    sa.Column('organ_4', sa.String(length=30), nullable=True),
    sa.Column('organ_5', sa.String(length=30), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('specie', sa.String(length=50), nullable=True),
    sa.Column('genus', sa.String(length=50), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('commonName', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_timestamp'), ['timestamp'], unique=False)

    op.create_table('plant_mini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('img_1', sa.String(length=100), nullable=False),
    sa.Column('organ_1', sa.String(length=30), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('specie', sa.String(length=50), nullable=True),
    sa.Column('genus', sa.String(length=50), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('commonName', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant_mini', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_mini_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('identification', schema=None) as batch_op:
        batch_op.drop_index('ix_identification_timestamp')

    op.drop_table('identification')
    with op.batch_alter_table('identification_mini', schema=None) as batch_op:
        batch_op.drop_index('ix_identification_mini_timestamp')

    op.drop_table('identification_mini')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identification_mini',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('img_1', sa.VARCHAR(length=100), nullable=False),
    sa.Column('organ_1', sa.VARCHAR(length=30), nullable=False),
    sa.Column('reliability', sa.FLOAT(), nullable=True),
    sa.Column('specie', sa.VARCHAR(length=50), nullable=True),
    sa.Column('genus', sa.VARCHAR(length=50), nullable=True),
    sa.Column('family', sa.VARCHAR(length=50), nullable=True),
    sa.Column('commonName', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('long', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identification_mini', schema=None) as batch_op:
        batch_op.create_index('ix_identification_mini_timestamp', ['timestamp'], unique=False)

    op.create_table('identification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('img_1', sa.VARCHAR(length=100), nullable=False),
    sa.Column('img_2', sa.VARCHAR(length=100), nullable=True),
    sa.Column('img_3', sa.VARCHAR(length=100), nullable=True),
    sa.Column('img_4', sa.VARCHAR(length=100), nullable=True),
    sa.Column('img_5', sa.VARCHAR(length=100), nullable=True),
    sa.Column('organ_1', sa.VARCHAR(length=30), nullable=False),
    sa.Column('organ_2', sa.VARCHAR(length=30), nullable=True),
    sa.Column('organ_3', sa.VARCHAR(length=30), nullable=True),
    sa.Column('organ_4', sa.VARCHAR(length=30), nullable=True),
    sa.Column('organ_5', sa.VARCHAR(length=30), nullable=True),
    sa.Column('reliability', sa.FLOAT(), nullable=True),
    sa.Column('specie', sa.VARCHAR(length=50), nullable=True),
    sa.Column('genus', sa.VARCHAR(length=50), nullable=True),
    sa.Column('family', sa.VARCHAR(length=50), nullable=True),
    sa.Column('commonName', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('long', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identification', schema=None) as batch_op:
        batch_op.create_index('ix_identification_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('plant_mini', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_mini_timestamp'))

    op.drop_table('plant_mini')
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_timestamp'))

    op.drop_table('plant')
    # ### end Alembic commands ###
