"""empty message

Revision ID: be3a95fdcc5e
Revises: ef4d98bbd2a7
Create Date: 2023-06-25 12:13:01.940744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3a95fdcc5e'
down_revision = 'ef4d98bbd2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identification_mini', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reliability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('specie', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('genus', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('family', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('commonName', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identification_mini', schema=None) as batch_op:
        batch_op.drop_column('commonName')
        batch_op.drop_column('family')
        batch_op.drop_column('genus')
        batch_op.drop_column('specie')
        batch_op.drop_column('reliability')

    # ### end Alembic commands ###
