"""empty message

Revision ID: dc5627021971
Revises: 
Create Date: 2023-06-27 16:40:23.826213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5627021971'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('img_1', sa.String(length=100), nullable=False),
    sa.Column('img_2', sa.String(length=100), nullable=True),
    sa.Column('img_3', sa.String(length=100), nullable=True),
    sa.Column('img_4', sa.String(length=100), nullable=True),
    sa.Column('img_5', sa.String(length=100), nullable=True),
    sa.Column('organ_1', sa.String(length=30), nullable=False),
    sa.Column('organ_2', sa.String(length=30), nullable=True),
    sa.Column('organ_3', sa.String(length=30), nullable=True),
    sa.Column('organ_4', sa.String(length=30), nullable=True),
    sa.Column('organ_5', sa.String(length=30), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('specie', sa.String(length=50), nullable=True),
    sa.Column('genus', sa.String(length=50), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('commonName', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_timestamp'), ['timestamp'], unique=False)

    op.create_table('genus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genus_name', sa.String(length=50), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specie_name', sa.String(length=50), nullable=True),
    sa.Column('common_name', sa.String(length=50), nullable=True),
    sa.Column('genus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genus_id'], ['genus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_mini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('img_1', sa.String(length=100), nullable=False),
    sa.Column('organ_1', sa.String(length=30), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('specie_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['specie_id'], ['specie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant_mini', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_mini_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_mini', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_mini_timestamp'))

    op.drop_table('plant_mini')
    op.drop_table('specie')
    op.drop_table('genus')
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_timestamp'))

    op.drop_table('plant')
    op.drop_table('family')
    # ### end Alembic commands ###
