"""empty message

Revision ID: de1b9c05300e
Revises: 94ace10098f0
Create Date: 2023-06-27 12:40:51.434161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1b9c05300e'
down_revision = '94ace10098f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('family')

    with op.batch_alter_table('genus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genus_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('genus')

    with op.batch_alter_table('plant_mini', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))

    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specie_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('common_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('specie')
        batch_op.drop_column('commonName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commonName', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('specie', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('common_name')
        batch_op.drop_column('specie_name')

    with op.batch_alter_table('plant_mini', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    with op.batch_alter_table('genus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genus', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('genus_name')

    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('family_name')

    # ### end Alembic commands ###
