"""empty message

Revision ID: e6dd35cd6e24
Revises: 7b2dad2d7478
Create Date: 2023-06-27 10:49:32.838833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6dd35cd6e24'
down_revision = '7b2dad2d7478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genus', sa.String(length=50), nullable=True),
    sa.Column('fk_family', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_family'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specie', sa.String(length=50), nullable=True),
    sa.Column('commonName', sa.String(length=50), nullable=True),
    sa.Column('fk_genus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_genus'], ['genus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant_mini', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_specie', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'specie', ['fk_specie'], ['id'])
        batch_op.drop_column('family')
        batch_op.drop_column('specie')
        batch_op.drop_column('commonName')
        batch_op.drop_column('genus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_mini', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genus', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('commonName', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('specie', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('family', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_specie')

    op.drop_table('specie')
    op.drop_table('genus')
    op.drop_table('family')
    # ### end Alembic commands ###
